modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

#issueTrackerURL="https://github.com/stancempire/enquestment/issues" #optional

[[mods]] #mandatory
	modId="${mod_id}" #mandatory
	version="${mod_version}" #mandatory
	displayName="${mod_name}" #mandatory
	#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
	#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
	#logoFile="" #optional
	#credits="" #optional
	authors="${mod_authors}" #optional
	#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)
	description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    mandatory=true #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

#[features.${mod_id}]
#openGLVersion="[3.2,)"
